Select 
 pid, 
 user_name, 
 starttime, 
 query, 
 query, 
 status 
from stv_recents 
where status='Running';
SELECT pg_terminate_backend(9840);
DROP TABLE jostens_stage.service_order;
CREATE TABLE jostens_stage.service_order(
  service_order_number bigint, 
  service_order_description varchar(100), 
  service_order_type varchar(30), 
  assignment_type varchar(30), 
  sales_rep_number bigint, 
  oracle_customer_number varchar(30), 
  order_group varchar(30), 
  event_code varchar(30), 
  event_desc varchar(30), 
  program_code varchar(30), 
  program_desc varchar(240), 
  status varchar(30), 
  reason varchar(30), 
  comments varchar(2000), 
  sales_year varchar(4), 
  ship_to_address_id bigint, 
  sold_to_address_id bigint, 
  bill_to_address_id bigint, 
  ship_to_contact varchar(100), 
  sold_to_contact varchar(100), 
  bill_to_contact varchar(100), 
  purchase_order_number varchar(50), 
  copy_from_service_order_number bigint, 
  orig_system_source varchar(30), 
  orig_system_reference varchar(240), 
  assigned_customer_service_team varchar(30), 
  customer_service_team_name varchar(80), 
  assigned_customer_service_rep bigint, 
  customer_service_rep_name varchar(80), 
  start_date_active timestamp, 
  end_date_active timestamp, 
  agreement_number varchar(50), 
  agreement_name varchar(50), 
  agreement_type_code varchar(30), 
  agreement_type_desc varchar(80), 
  agreement_price_list varchar(255), 
  agreement_terms varchar(15), 
  agreement_start_date_active timestamp, 
  agreement_end_date_active timestamp, 
  product_offering_usage varchar(30), 
  pricing_method varchar(30), 
  special_instructions varchar(4000), 
  packing_method varchar(80), 
  packing_instructions varchar(350), 
  ship_method_code varchar(30), 
  ship_method_desc varchar(80), 
  shipping_instructions varchar(350), 
  freight_terms varchar(30), 
  invoice_frequency varchar(30), 
  invoice_comments varchar(240), 
  commission_program varchar(30), 
  primary_service_order_flag varchar(1), 
  annual_roll_flag varchar(1), 
  order_line_summarization_flag varchar(1), 
  warehouse_id bigint, 
  consolidated_ship_warehouse_id bigint, 
  recg_tape_frequencies varchar(150), 
  recg_solicit_frequencies varchar(150), 
  recg_ship_frequencies varchar(150), 
  recg_down_select varchar(150), 
  recg_award_wo_logo varchar(150), 
  recg_dedicated_800_number varchar(150), 
  recg_fax_number varchar(150), 
  recg_ivr_number varchar(150), 
  recg_web_site varchar(150), 
  recg_crm varchar(150), 
  service_order_type1 varchar(30), 
  service_order_type2 varchar(30), 
  sales_rep_transaction_type varchar(10), 
  created_by varchar(100), 
  creation_date timestamp, 
  first_activated_by varchar(100), 
  first_activation_date timestamp, 
  price_builder varchar(30), 
  dipl_rolled_from_service_order varchar(150), 
  dipl_grouping varchar(150), 
  ybms_job_number varchar(150), 
  ybms_yearbook_year varchar(150), 
  ybms_plant varchar(150), 
  ybms_program varchar(150), 
  ybms_trim_size varchar(150), 
  ybms_pages bigint, 
  ybms_copies varchar(150), 
  ybms_yeartech_online varchar(150), 
  ybms_contract_ship_date varchar(150), 
  annc_web_catalog_flag varchar(1), 
  gt_po_number_required varchar(1), 
  regalia_email_address varchar(150), 
  contact_name varchar(150), 
  contact_email_address varchar(150), 
  contact_phone varchar(150), 
  contact_fax varchar(150), 
  scheduling_offset_days varchar(150), 
  homeship_flag varchar(1), 
  context varchar(150), 
  attribute1 varchar(150), 
  attribute2 varchar(150), 
  attribute3 varchar(150), 
  attribute4 varchar(150), 
  attribute5 varchar(150), 
  attribute6 varchar(150), 
  attribute7 varchar(150), 
  attribute8 varchar(150), 
  attribute9 varchar(150), 
  attribute10 varchar(150), 
  attribute11 varchar(150), 
  attribute12 varchar(150), 
  attribute13 varchar(150), 
  attribute14 varchar(150), 
  attribute15 varchar(150), 
  attribute16 varchar(150), 
  attribute17 varchar(150), 
  attribute18 varchar(150), 
  attribute19 varchar(150), 
  attribute20 varchar(150), 
  attribute21 varchar(150), 
  attribute22 varchar(150), 
  attribute23 varchar(150), 
  attribute24 varchar(150), 
  attribute25 varchar(150), 
  attribute26 varchar(150), 
  attribute27 varchar(150), 
  attribute28 varchar(150), 
  attribute29 varchar(150), 
  attribute30 varchar(150),
  PRIMARY KEY (service_order_number)
);
TRUNCATE TABLE  jostens_stage.service_order ;
​
COPY jostens_stage.service_order
FROM 's3://jostens-data-dev-analysis/service_order/'
FORMAT AS PARQUET
IAM_ROLE 'arn:aws:iam::147913565791:role/redshift-iam-role-s3-glue-athena' ;
​
SELECT COUNT(*) FROM jostens_stage.service_order;
DROP TABLE IF EXISTS jostens.service_order CASCADE; 
​
CREATE TABLE jostens.service_order
SORTKEY (service_order_number) 
AS 
SELECT  *
FROM  jostens_stage.service_order  ;
​
select * from jostens.service_order limit 5;
select count(*) from jostens.service_order limit 5;

--data type
select pg_get_cols ('jostens.service_order');