CREATE TABLE IF NOT EXISTS   jostens_stage.order_header
(
  bridge_order_number BIGINT, 
  sales_rep_number VARCHAR (2000), 
  oracle_customer_number VARCHAR (2000), 
  service_order_number bigint, 
  oracle_order_number bigint, 
  order_entered_date VARCHAR (2000), 
  order_requested_delivery_date VARCHAR (2000), 
  order_scheduled_ship_date VARCHAR (2000), 
  order_created_date VARCHAR (2000), 
  order_imported_date DOUBLE PRECISION, 
  order_cycle_duration DOUBLE PRECISION, 
  order_group VARCHAR (2000), 
  order_type VARCHAR (2000), 
  order_class VARCHAR (2000), 
  order_source VARCHAR (2000), 
  status VARCHAR (2000), 
  status_reason VARCHAR (2000), 
  prepaid_ind VARCHAR (2000), 
  sales_channel VARCHAR (2000), 
  customer_service_team_name VARCHAR (2000), 
  return_number bigint, 
  creation_code VARCHAR (2000), 
  creation_reason VARCHAR (2000), 
  collection_doc_replace_flag VARCHAR (2000), 
  collection_doc_exclude_flag VARCHAR (2000), 
  shipment_priority_code VARCHAR (2000), 
  greg_who VARCHAR (2000), 
  greg_order_number VARCHAR (2000), 
  greg_what_was_ordered VARCHAR (2000), 
  greg_what_was_received VARCHAR (2000), 
  yb_job_number VARCHAR (2000), 
  yb_file_year VARCHAR (2000), 
  yb_customer_number VARCHAR (2000), 
  yb_advisor_name VARCHAR (2000), 
  yb_customer_phone_number VARCHAR (2000), 
  yb_plant_code VARCHAR (2000), 
  yb_jds_vendor VARCHAR (2000), 
  order_receipt_method VARCHAR (2000), 
  sales_rep_transaction_type VARCHAR (2000), 
  annc_add_order VARCHAR (2000), 
  annc_closed_date VARCHAR (2000), 
  annc_what_was_ordered VARCHAR (2000), 
  annc_what_was_received VARCHAR (2000), 
  dipl_who VARCHAR (2000), 
  dipl_order_number VARCHAR (2000), 
  dipl_what_was_ordered VARCHAR (2000), 
  dipl_what_was_received VARCHAR (2000), 
  ordered_by_name VARCHAR (2000), 
  ordered_by_phone VARCHAR (2000), 
  ordered_by_email VARCHAR (2000), 
  combined_bridge_order bigint, 
  combined_order_flag VARCHAR (2000), 
  created_by VARCHAR (2000), 
  creation_date VARCHAR (2000), 
  comments VARCHAR (2000), 
  lfxp_who VARCHAR (2000), 
  lfxp_order_number VARCHAR (2000), 
  lfxp_what_was_ordered VARCHAR (2000), 
  lfxp_what_was_received VARCHAR (2000), 
  bridge_order_grad_date VARCHAR (2000), 
  grad_year DOUBLE PRECISION, 
  source_order_reference VARCHAR (250), 
  ybms_job_number VARCHAR (2000), 
  ybms_yearbook_year VARCHAR (2000), 
  ybms_plant VARCHAR (2000), 
  ybms_program VARCHAR (2000), 
  ybms_trim_size VARCHAR (2000), 
  ybms_pages VARCHAR (2000), 
  ybms_copies VARCHAR (2000), 
  ybms_large_label_qty VARCHAR (2000), 
  ybms_small_label_qty VARCHAR (2000), 
  ybms_yeartech_online VARCHAR (2000), 
  ybms_service_order_id VARCHAR (2000), 
  ybms_mf_kit_reques_date VARCHAR (2000), 
  ybms_commission_pct VARCHAR (2000), 
  ybms_yto_indicator VARCHAR (2000), 
  op_received_date VARCHAR (2000), 
  mfg_instructions VARCHAR (1000), 
  greg_grad_type_date VARCHAR (2000), 
  submitter_type VARCHAR (2000), 
  shop_handling_code VARCHAR (2000), 
  last_update_date VARCHAR (2000), 
  schedule_type VARCHAR (2000), 
  purchase_order_number VARCHAR (2000), 
  zdp_indicator VARCHAR (2000), 
  zdp_status VARCHAR (2000), 
  sample_order_type VARCHAR (2000), 
  owms_team VARCHAR (2000), 
  owms_order_category VARCHAR (2000), 
  owms_order_type VARCHAR (2000), 
  owms_job_num VARCHAR (2000), 
  owms_stuff_date VARCHAR (2000), 
  owms_cd_code VARCHAR (2000), 
  owms_order_info VARCHAR (2000), 
  merge_eligible_flag VARCHAR (2000), 
  combined_ndpd_ind VARCHAR (2000),
  PRIMARY KEY (bridge_order_number)
);



