CREATE EXTERNAL TABLE rawdb.item (
  INVENTORY_ITEM_ID bigint,
  ORGANIZATION_ID bigint,
  COGS_CODE_COMBINATION_ID bigint,
  SALES_CODE_COMBINATION_ID bigint,
  EXPENSE_CODE_COMBINATION_ID bigint,
  ORGANIZATION_CODE varchar(3)),
  ORGANIZATION_NAME varchar(60),
  ITEM_NUMBER varchar(50),
  STD_LOT_SIZE bigint,
  DESCRIPTION varchar(240),
  ITEM_TYPE varchar(80),
  ITEM_STATUS varchar(10),
  UNIT_WEIGHT bigint,
  WEIGHT_UOM_CODE varchar(10),
  INVENTORY_CATEGORY varchar(50),
  PURCHASING_CATEGORY varchar(50),
  GL_PRODUCT_CATEGORY varchar(50),
  PROD_CLASS_CATEGORY varchar(50),
  PROD_SUB_CATEGORY varchar(50),
  PURCHASING_SUB_CLASS varchar(40),
  STRUCTURE_NAME varchar(30),
  PRIMARY_UNIT_OF_MEASURE varchar(25),
  GENERIC_FLAG varchar(1),
  COSTING_ENABLED_FLAG varchar(1),
  INVENTORY_ASSET_FLAG varchar(1),
  DROPSHIP_FLAG varchar(1),
  PLANNING_MAKE_BUY varchar(5),
  MATERIAL_COST varchar(22),
  RESOURCE_COST varchar(22),
  OUTSIDE_PROCESSING_COST varchar(22),
  MATERIAL_OVERHEAD_COST varchar(22),
  OVERHEAD_COST varchar(22),
  FIXED_OVERHEAD_COST bigint,
  VARIABLE_OVERHEAD_COST bigint,
  ITEM_COST bigint,
  DESCRIPTOR_INVOICE_USAGE varchar(240),
  ITEM_TYPE_ID bigint,
  SHIPPABLE_ITEM_FLAG varchar(1),
  MIN_MINMAX_QUANTITY bigint,
  MAX_MINMAX_QUANTITY bigint,
  LOT_CONTROL_CODE bigint,
  FULL_LEAD_TIME bigint,
  COVER_SIZE varchar(50),
  DIMENSIONS varchar(50),
  ITEM_SIZE varchar(50),
  STYLE varchar(50),
  TYPE varchar (50),
  MATERIAL varchar(50),
  COLOR varchar(50),
  DEGREE varchar(50),
  LOT_SIZE varchar(50),
  APPAREL_COLOR varchar(50),
  APPAREL_SIZE varchar(50),
  QUALITY varchar(50),
  DIPL_ITEM_TYPE varchar(80),
  DIPL_ITEM_TYPE2 varchar(80),
  LENGTH varchar(50),
  METAL_QUALITY varchar(50),
  DESIGN varchar(240),
  TRIM_SIZE varchar(240))
STORED AS PARQUET
LOCATION 's3://jostens-data-dev-raw/item/test/'



